[package]
name = "hangman_words"
version = "0.1.0"
authors = ["Quentin Boyer <qbsecond@gmail.com>"]
edition = "2018"
description = "Hangman helper for solving and finding difficult words"

[dependencies]
clap = "2.32"
regex = "1.1"
yaml-rust = "0.4"
